# -*- mode: Python -*

TARGET_ARCH = 'arm64'

ENV = 'local'
OPENAI_API_KEY=os.getenv('OPENAI_API_KEY', '')
AWS_ACCESS_KEY_ID=os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY=os.getenv("AWS_SECRET_ACCESS_KEY", '')
REGION=os.getenv('REGION', 'ap-south-1')
LLM_MODEL=os.getenv('LLM_MODEL', 'bedrock/anthropic.claude-3-haiku-20240307-v1:0')
S3_BUCKET=os.getenv('S3_BUCKET', '')
S3_PREFIX=os.getenv('S3_PREFIX', 'up-rera-projects')

app_config_map_data = {
    'ENV': ENV,
    'OPENAI_API_KEY': OPENAI_API_KEY,
    'AWS_ACCESS_KEY_ID': AWS_ACCESS_KEY_ID,
    'AWS_SECRET_ACCESS_KEY': AWS_SECRET_ACCESS_KEY,
    'REGION': REGION,
    'LLM_MODEL': LLM_MODEL,
    'S3_BUCKET': S3_BUCKET,
    'S3_PREFIX': S3_PREFIX,
}


load('ext://namespace', 'namespace_create', 'namespace_inject')

namespace = 'up-rera-scraper-app-runner'
namespace_create(namespace)


load('ext://configmap', 'configmap_from_dict')


app_configmap = configmap_from_dict('app-config', inputs=app_config_map_data)
k8s_yaml(namespace_inject(app_configmap, namespace))


yaml = kustomize('./terraform/app-deploy/manifests/tilt')
k8s_yaml(namespace_inject(yaml, namespace))

docker_build('up-rera-scraper-app-runner', '.',
    dockerfile='Dockerfile',
    target='localdev',
    live_update=[
        sync('.', '/scrapers/up-rera-scraper-app-runner'),
    ], build_args={
        'TARGET_ARCH': TARGET_ARCH,
    })


k8s_resource('up-rera-scraper-app-runner', port_forwards='8080:8080')

